title: Posts
description: My Posts
author: Prasanna Dhongudi Sudhindrakumar
github: https://github.com/prasanna-ds
about: I'm a Data Engineer, Programmer. I work on data related tech stack, Cloud, Python and Scala
disqus_shortname: prasanna

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/prasanna-dhongudi-sudhindrakumar-67939797/"
    - icon: fa-github
      link: "https://github.com/prasanna-ds"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://prasanna-ds.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
